import "./globals.css";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ChatProvider } from "../context/chatContext";
import { UserProvider } from "../context/authContext";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body>  */}
      <body> <UserProvider>
          <ChatProvider>{children}</ChatProvider>
        </UserProvider></body>
    </html>
  );
}
